server.port=8080

spring.application.name=olap-agent-poc

# TABULAR | MULTIDIMENSIONAL
ssas.model-type= TABULAR
ssas.datasource= localhost
ssas.catalog= SalesSemanticModel
ssas.timeout-seconds= 30
ssas.username= your_username
ssas.password= your_password

logging.level.root= INFO
logging.level.com.example.olapagent= DEBUG
